# Generated by Django 3.2 on 2023-06-26 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=255)),
                ('b_building_no', models.CharField(max_length=255)),
                ('b_st', models.CharField(max_length=255)),
                ('b_area', models.CharField(max_length=255)),
                ('b_city', models.CharField(max_length=255)),
                ('b_country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=255)),
                ('e_age', models.IntegerField()),
                ('e_email', models.EmailField(max_length=255)),
                ('e_phone_number', models.CharField(max_length=20)),
                ('e_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRApp.branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='b_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRApp.employee'),
        ),
    ]
